repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: name-tests-test
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-case-conflict
      - id: check-toml
      - id: check-merge-conflict
      - id: check-xml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: check-symlinks
      - id: mixed-line-ending
      - id: sort-simple-yaml
      - id: fix-encoding-pragma
        args:
          - --remove
      - id: pretty-format-json
        args:
          - --autofix

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-check-blanket-noqa
      - id: python-check-mock-methods
      - id: python-no-eval
      - id: python-no-log-warn

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: Run isort to sort imports
        files: \.py$
        exclude: ^build/.*$|^.tox/.*$|^venv/.*$
        args:
          - --lines-after-imports=2
          - --profile=black
          - --line-length=80

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.286
    hooks:
      - id: ruff
        types_or: [python, pyi, jupyter]
        args:
          - --fix
          - --target-version=py311
          - --select=B,C,E,F,W
          - --line-length=80

  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args:
          - --ignore=E203,E402,E501,E800,W503,W391,E261
          - --select=B,C,E,F,W,T4,B9

  - repo: https://github.com/Riverside-Healthcare/djLint
    rev: v1.32.1
    hooks:
      - id: djlint-reformat
        pass_filenames: false
        args:
          - incident_reporting/templates
          - --format-css
          - --profile=jinja
          - --indent=2
          - --quiet
      - id: djlint
        require_serial: true
        pass_filenames: false
        args:
          - incident_reporting/templates
          - --profile=jinja
          - --use-gitignore
          - --ignore=H006,T028,H031,H021,H013,H011

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        files: incident_reporting/static/js/, incident_reporting/static/css/
        args:
          - --no-config

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.55.0
    hooks:
      - id: eslint
        files: incident_reporting/static/js/
        args:
          - --no-eslintrc
          - --env=es2024

  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        args:
          - --safe
          - --target-version=py311
          - --line-length=80
