runtime: python311
instance_class: F2
entrypoint: gunicorn --worker-class uvicorn.workers.UvicornWorker --bind :$PORT incident_reporting.main:app

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 5

env_variables:
  GCP_DEPLOY: True

handlers:
- url: /.*
  script: auto
