steps:
  - name: 'python:3.11'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        python -m venv /workspace/venv
        source /workspace/venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', '--quiet']

artifacts:
  objects:
    location: 'gs://$PROJECT_ID-build-artifacts/$BUILD_ID/'
    paths: ['**/*']

timeout: '900s'
