[tool.poetry]
name = "ucpd-incident-reporting"
version = "0.1.0"
description = "This application makes use of scraped incidents from the UCPD Daily Incident Reports and displays them in a handful of ways."
authors = ["michplunkett"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
requests = "^2.28.2"
pytest = "^7.3.1"
responses = "^0.23.1"
pre-commit = "^3.4.0"
streamlit = "^1.27.2"
google-cloud-ndb = "^2.2.2"
google-cloud-logging = "^3.8.0"
pytz = "^2023.3.post1"
cachetools = "^5.3.1"
polars = "^0.19.7"
watchdog = "^3.0.0"
dash = "^2.14.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
