name: Deploy to App Engine
on:
#  push:
#    tags:
#      - 'v[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    name: Deploying to Google Cloud
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Authenticate on GCP
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_POOL }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Deploy to App Engine
        id: deploy
        uses: 'google-github-actions/deploy-appengine@v2'

      # Example of using the output
      - name: Testing Status Endpoint
        id: test
        run: 'curl "${{ steps.deploy.outputs.version_url }}/status"'
