name: Deploy to App Engine
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Deploying to Google Cloud
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}'
          project_id: '${{ secrets.GCP_PROJECT_ID }}'

      - name: Deploy to App Engine
        id: deploy
        uses: 'google-github-actions/deploy-appengine@v2'

      # Example of using the output
      - name: Testing Status Endpoint
        id: test
        run: 'curl "${{ steps.deploy.outputs.version_url }}/status"'
